### ISSUE TITLE
[4.0] Middleware Pipeline

### ISSUE THREAD

**Issue by RomainLanz** [adonisjs/discussion#13]
Hey everyone!

Middleware Pipeline is a feature thought by @thetutlage that could push the performance of your application by a LOT.

Currently, all middlewares are run one by one and could slow down your application. The Middleware Pipeline could let you create multiple pipeline that will run in parallel.

Here's a transcript of the private discussion I got with @thetutlage :

> **thetutlage**
> Also I am expermenting around parllel middleware
> 80% of the middleware are not dependent upon each other, so executing them in sequence is overkill
> Making them parallel will be huge performance boost.
> What I have in mind is.. Piplelines + Middleware
> Each pipeline will be executed in sequence and it can have multiple middleware, they will be executed in parallel
> So If u want 2 middleware to be executed in sequence, you can put them in 2 pipelines
> So middleware like *Shield + Flash + AuthInit* will be in a single pipeline
> And *Cors* will be in a different pipeline, since it has the ability to end the request of it’s own.

**Comment by thetutlage** [comment]
I recently published this library [co-compose](https://www.npmjs.com/package/co-compose) Which has support for registering/running middleware + pipelines.

Currently it only supports `ES2015` generators and I will be adding support for `async/await` too, coz that what AdonisJs will be making use of.

## What are Middleware?
Middleware are a sequence of operations to be occurred before taking the final action. For example:

1. Http middleware to transform the request before it reaches the controller action.
2. Lucid model hooks to transform the data before it reaches the `create/update` methods.

Some operations especially in HTTP requests can be parallelized, instead of running them in sequence. For example:

Flash middleware to read the session values and wipe of session store can run in parallel with the Shield middleware, which is responsible for adding security headers to the response object.

## What are Pipelines?

Pipelines are a way to run these middleware in parallel. Pipelines comes with zero overhead, since the middleware signature remains the same and as the author of the middleware, you won't have to do anything special for pipelines.

The consumer of the middleware can decide which all middleware should go in one pipeline.

### Gains

1. The performance of an HTTP request will improve, since some operations will be parallelized.

### Loss

1. The consumer have to put some thoughts into, how to structure pipelines. The benefit Adonis has is the closed ecosystem, where the authors for the middleware can make it clear in the documentation, how the middleware should be used.
