### ISSUE TITLE
Allow semicolons with flag 

### ISSUE THREAD

**Issue by nrempel** [adonisjs/discussion#28]
How do you feel about allowing semicolons with a flag or as an option?

This could use https://github.com/Flet/semistandard.

It's the same rules as standard but uses semicolons. I'm all for opinionated linting rules but personally I much prefer semicolons. The rest of the `standard` rules are fine for me (anything consistent).

**Comment by thetutlage** [comment]
You can use whatever you want in your project, Adonisjs doesn't stops you.

**Comment by nrempel** [comment]
Thanks, I do currently use semicolons and other linting rules.

What I meant to say was allow the code generator to produce semi colons.

**Comment by chrisrickard** [comment]
+1, I think it's a [matter of preference](https://medium.com/@kentcdodds/semicolons-in-javascript-a-preference-dd8fc8b80895) - and for a project built for peeps to use, it would be great if it was an option for Ace generated code.

**Comment by watzon** [comment]
Idk, seems like a lot of work for little return to me. I understand having your own coding style, but maybe it would make more sense to create a provider (if possible) that overrides the default templates and replaces them with templates that include semi-colons?

**Comment by thetutlage** [comment]
I call it Javascript Fatigue, we just go too far with these things. The only reason I choose https://standardjs.com is coz it doesn't comes with a config file and hence you cannot customize it.

I am not imposing my styles on others, but instead of adding a new feature to `adonis-cli` which dynamically generates the blueprint by taking 20 options from the user, I will better focus on building something that is useful.

**Comment by nrempel** [comment]
Agreed. Decision fatigue is important to avoid. I'll close this issue.
