### ISSUE TITLE
Authorization, profiler/logging, serialization, API docs

### ISSUE THREAD

**Issue by bjunc** [adonisjs/discussion#38]
I'm newly investigating Adonis.  I have a lot of experience in Vue (Backbone before that, AS3/Flex before that), and the Adonuxt page is what exposed me to Adonis (looks awesome!).  On the framework side, I'm largely used to Symfony 2/3.  The concept of Adonis sounds really intriguing, however I feel like maybe I am missing some features I have become used to with Symfony.  Maybe I just don't see the docs for these features, maybe these features are irrelevant in Adonis, or maybe they're in the pipeline, etc..  If someone close to the project could shed light, I'd appreciate it.

#### Authorization (permissions)

I see the section on Authentication, but what about Authorization?  If you want to block routes by a user role, do you need to write your own middleware?  What about individual resources?  Symfony uses the concept of [voters](http://symfony.com/doc/current/security/voters.html) which can take an `attribute` and a `subject` (ie. resource), and run it through a voting process (true/false). 

#### Profiler / logging

With Symfony, I get a nice little floating footer that shows query count, execution time, memory usage, caching summary, and auth tokens.  I can also simulate a user by appending `?_switch_user={username}`.  All of which can be clicked through to `/_profiler`.  How do you guys do this?

#### Serialization / Deserialization

I'm not overly familiar with Laravel, which I know Adonis takes some queues from.  However, there seems to be some magic going on with serialization/deserialization; without any explanation on how that happens, or if there is a way to jump in there to tweak it.  Again referencing Symfony, but serialization can be done through "groups".  These groups can cover different contexts, and you can create custom serializers/deserializers to handle circular references, etc..  I see the `hidden()` and `visible()` static methods, but is that it?

#### API

Lastly, I would suggest another version of the docs that are strictly API based.  I think Vue does a pretty good job with this.  Basically, there is a "guide", which is written using examples; which I think the current Adonis docs seem to fit.  Then, there is an API section, where it's less conversational, and exposes all properties, methods, events, etc..  Where can I go to just see what properties / methods exist on a Lucid Model, or Controller?

Thanks in advance.

**Comment by webdevian** [comment]
> Where can I go to just see what properties / methods exist on a Lucid Model, or Controller?

I completely agree with this, several times I've had to dig in to the source code to see what a method does and what parameters it takes. API docs would make learning Adonis easier

**Comment by thetutlage** [comment]
@bjunc 

Yup part of the stuff is in pipeline, lemme answer them one by one.

#### Authorization (permissions)

There is no support for it as of now, but with the newer release I am going to create a module for **Authorization** as well. Not sure how similar it will be with Symfony, but yes, it will let you take actions based upon user roles.

#### Profiler / logging

I have added `Logger` module for Adonis-4.0 https://github.com/adonisjs/adonis-framework/tree/dawn/src/Logger. It takes driver based approach to add new drivers and switch them using the config file.

I am not much familiar with profilers much, since in Node.js world things are async and hard to track things for a single request. Since Node.js has added support for `Async hooks` https://nodejs.org/dist/latest-v8.x/docs/api/async_hooks.html, it will be easier to track things, but the API itself is **experimental**, so I have to wait for a while.

#### Serialization / Deserialization
Yes, Lucid uses Serializers internally but not exposed as an API. In couple of months you can expect the API to be exposed publicly with couple of in-built serializers, like **Simple** and one that follows the specs of **JSON API**

#### API
All methods are documented properly using docblocks and I will be releasing API DOCS with 4.0 release ( they won't be pretty now, since YUI DOCS theme kind of sucks )

**Comment by bjunc** [comment]
That all sounds promising.  Thanks for taking the time to address each one.  Looking forward to 4.0.  I'm currently doing a lot of work in Vue, and will likely be using Nuxt in large production apps soon.  When v4.0 of Adonis comes out, it'd be great to see if it can be used as the middleware.
