### ISSUE TITLE
modify response

### ISSUE THREAD

**Issue by 2peter3** [adonisjs/discussion#44]
hello,
ive a short question about adonisjs, is it possible to modify rendered views? as example:

my TestController:
```js
  * test (request, response) {
      yield response.sendView('welcome');
  }
```

routes.js 

```js
Route.get('/', 'TestController.test')
```

Http.js

```js
Http.onStart = function () {
  const Response = use('Adonis/Src/Response')
  Response.macro('sendView', function (template, options) {
    const View = use('View')
    const compiledHtml = yield View.make('welcome')
    return compiledHtml;
    return 
  })
}
```

but this method wont work. i need to modify all views from "response.sendView" and append a text to the sourcecode.

is it possible to do this with Http.onStart and Response.macro?

**Comment by thetutlage** [comment]
Please consider creating issues in the actual repo over this one, since we use it for discussing missing or upcoming features.

So what you need is the control over the output of `rendered view` and append your own HTML to it, before showing it to the user.

What you can do is add your own macro which makes the view and then send it as response.

```js
Response.macro('myView', function * (template, options) {
   let html = yield this.view(template, options)
   html = `${html} <h2> Appended html </h2>`
  this.send(html)
})
```

And use it inside your controllers

```js
yield response.myView('welcome')
```
